.env
package-lock.json
package.json
src/App.js
src/page/admin/adminNav.jsx
src/page/admin/course/add/offerableCourseAdd.css
src/page/admin/course/add/offerableCourseAdd.jsx
src/page/admin/course/edit/offerableCourseEdit.jsx
src/page/admin/course/offerableCourses.css
src/page/admin/course/offerableCourses.jsx
src/page/admin/management/aggregateTable.css
src/page/admin/management/courses/add/courseAdd.css
src/page/admin/management/courses/add/courseAdd.jsx
src/page/admin/management/courses/courses.css
src/page/admin/management/courses/courses.jsx
src/page/admin/management/courses/edit/courseEdit.jsx
src/page/admin/management/providers/add/providerAdd.css
src/page/admin/management/providers/add/providerAdd.jsx
src/page/admin/management/providers/edit/providerEdit.jsx
src/page/admin/management/providers/providers.css
src/page/admin/management/providers/providers.jsx
src/utils/requests.js

Readied for User page table.
Need to add edit/add/delete still

Page for all providers and Courses

---

src/page/admin/adminNav.css
src/page/admin/adminNav.jsx
src/page/admin/course/add/offerableCourseAdd.css
src/page/admin/course/add/offerableCourseAdd.jsx
src/page/admin/course/edit/offerableCourseEdit.jsx
src/page/admin/course/offerableCourses.jsx
src/page/admin/management/courses/add/courseAdd.css
src/page/admin/management/courses/add/courseAdd.jsx
src/page/admin/management/courses/courses.jsx
src/page/admin/management/courses/edit/courseEdit.jsx
src/page/admin/management/providers/add/providerAdd.css
src/page/admin/management/providers/add/providerAdd.jsx
src/page/admin/management/providers/edit/providerEdit.jsx
src/page/admin/management/providers/providers.jsx
src/page/search/search.css
src/page/search/search.jsx
src/utils/commonRequests.js

Added skeletons/preblocking to
-admin
--offerablecourses table
---edit
---add
--courses table
---edit
---add
--providers table
---edit
---add
-search
Ready to merge changes, create new issues for pre-blocking coursePage, Index, User, etc.

81 pre blocking

---

src/component/courseProviderCard/courseProviderCard.jsx
src/component/modals/auth/login.jsx
src/dataSlice.js
src/page/checkout.jsx
src/page/course/course.jsx
src/page/orderComplete.jsx

Fixed checkout now adding the purchased course to user_course, user ID and Email is now stored in a redux object

user Redux and user_course updating based on purchase

---

src/App.jsx
src/component/modals/deleteModal.jsx
src/page/admin/adminNav.jsx
src/page/admin/management/courses/edit/courseEdit.jsx
src/page/admin/management/users/edit/editUser.css
src/page/admin/management/users/edit/editUser.jsx
src/page/admin/management/users/users.css
src/page/admin/management/users/users.jsx
src/page/layout.css
src/page/layout.jsx
src/styles.css
src/utils/Classes/commonClasses.js
src/utils/commonRequests.js
src/utils/requests.js

- **added users table and edit page, need to implement changing of roles for userpage and deletion of user**
- **work on role management**
- **added roles to user edit page, fixed profile picture in navbar**
- **added skeleton to user page**
- **added deletion of users**

64 users admin page

---

src/component/Rating/review.css
src/component/modals/auth/login.jsx
src/dataSlice.js
src/page/checkout.css
src/page/checkout.jsx
src/page/layout.jsx
src/page/userPage.css
src/page/userPage.jsx

Changed some things in checkout to line up elements better.
Added image link to the userDto, allowing showing of user profile picture without API call.

Checkout styling fix and user page image

---

src/component/card/card.css
src/component/card/card.jsx
src/component/card/courseCard.css
src/component/card/courseCard.jsx
src/page/search/search.jsx

- **styled cards more uniformly for images**
- **updated card styling for horizontal reactive styling**

122 filter page dropdown

---

src/component/Rating/review.jsx
src/component/Rating/reviewWriter.css
src/component/Rating/reviewWriter.jsx
src/component/courseProviderCard/courseProviderCard.css
src/component/courseProviderCard/courseProviderCard.jsx
src/page/course/course.css
src/page/course/course.jsx
src/page/course/reviewSection.css
src/page/course/reviewSection.jsx
src/styles.css

- **removed global a text decoration styling**
- **updated styling of course page, fixed filtering and styling problems in review component**
- **fixed key errors**
- **updated styling on ProviderCards**

course page styling

---

src/page/admin/management/courses/add/courseAdd.jsx
src/page/admin/management/courses/edit/courseEdit.jsx
src/page/course/course.jsx
src/utils/commonRequests.js

- **implemented retrieval of keywords for course**
- **added keyword functionality to edit and add courses page**

course form keywords

---

src/component/modals/auth/login.jsx
src/component/modals/auth/register.jsx
src/page/admin/course/add/offerableCourseAdd.jsx
src/page/admin/course/edit/offerableCourseEdit.jsx
src/page/admin/management/courses/add/courseAdd.jsx
src/page/admin/management/courses/edit/courseEdit.jsx
src/page/admin/management/providers/add/providerAdd.jsx
src/page/admin/management/providers/edit/providerEdit.jsx
src/page/admin/management/users/edit/editUser.jsx
src/pages/Index.html
src/pages/addCourse.html
src/pages/homepage.css
src/pages/login.html

- **no alerts on successful submit, only on error**
- **removed catch clause as it ran regardless of outcome**
- **removed old TODO**

145 form alerts

---

src/page/index.jsx
src/page/userPage.jsx

fixed issue with entire profile picture object being saved in redux

---

src/component/Rating/review.css
src/component/Rating/review.jsx
src/component/favoriteCard/favoriteCard.css
src/component/favoriteCard/favoriteCard.jsx
src/page/course/reviewSection.css
src/page/userPage.css
src/page/userPage.jsx

- **fixed linking to wrong page from reviews**
- **started work on styling userPage**
- **fixed favorites image scaling**
- **previous courses now has icons**
- **added gap to user caret**

157 userpage fixes

---

src/component/favorite/favoriteButton.jsx
src/page/course/course.jsx
src/page/course/reviewSection.jsx
src/page/userPage.jsx

fixed the favorite api calls to be consistent with the rest of the project

---

src/component/Rating/review.jsx
src/page/course/reviewSection.jsx
src/page/layout.jsx
src/page/userPage.jsx
src/utils/commonRequests.js
src/utils/requests.js

Forces the user to logout and redirect them to index if a 403 was received while the user is logged in.

Force logout on 403

---

src/component/modals/confirmChoice/confirmChoiceDialog.css
src/component/modals/confirmChoice/confirmChoiceDialog.jsx
src/page/course/reviewSection.css
src/page/course/reviewSection.jsx
src/page/userPage.css
src/page/userPage.jsx
src/utils/requests.js

- added new component modal for confirming destructive actions
- fixed confirm choice dialog on user page

confirmChoiceDialog

---

src/page/admin/management/courses/edit/courseEdit.jsx
src/utils/commonRequests.js

- **updated dropdown links on navbar**
- **changed formatting for userpage if user has no courses**
- **updated styling for cta buttons on main page**
- **fixed put endpoint for course edit**

course edit put

---

src/component/card/courseCard.css
src/page/Index.css
src/page/layout.css
src/page/layout.jsx

- **updated navbar to scale better with smaller screens**
- **fixed size for image slideshow index**
- **removed resizing animation for course card index page**

navbar fixes

---

src/component/modals/auth/login.jsx
src/component/modals/auth/register.jsx
src/page/admin/course/edit/offerableCourseEdit.jsx
src/page/course/course.jsx
src/page/layout.jsx
src/page/search/search.jsx
src/utils/authentication/authentication.js
src/utils/commonRequests.js

- **updated so providers are hidden if offerable course is hidden on course page**
- **updated navigate for offerableCourse edit**

course page offerable fix

---

src/page/checkout/checkout.jsx

- fixed deprecated api call in checkout
-  Fixed required fields in checkout

checkoutApiFix

---

src/page/checkout/checkout.jsx

- fixed checkout CVC code input not working

Checkout fix

---

src/component/modals/deleteModal.jsx
src/page/admin/course/offerableCourses.jsx
src/page/admin/management/courses/courses.jsx
src/page/admin/management/providers/providers.jsx

- **removed deletion functionality from providers, courses and offerable courses to allow historical data. Offerable courses should use visible instead of deletion**

delete modal warning
